repos:
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.1
    hooks:
    - id: mdformat
      exclude: "CHANGELOG.md"
      additional_dependencies:
      - mdformat-tables
      - mdformat-config
      - mdformat-frontmatter
      - mdformat-gfm

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0  # Use the ref you want to point at
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: no-commit-to-branch
        args: [--branch, develop, --branch, main]