repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0  # Use the ref you want to point at
    hooks:
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-yaml
        args: ['--unsafe']
      - id: no-commit-to-branch
        args: [--branch, main]