---
name: Build the website

on:
  push:
    branches:
      - main
jobs:
  deploy_website:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        token: ${{ secrets.WRITE_PAT }} 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: make install
    - name: Setup doc deploy
      run: |
        git config --global user.name "semantic-release (via Github actions)"
        git config --global user.email "semantic-release@australiacloud.com.au"
    - name: Build the docs site.
      shell: bash    
      run: |
        make docs-build
