---
name: Check the website builds
on:
  pull_request:
    branches:
      - main
jobs:
  check_links:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        token: ${{ secrets.WRITE_PAT }} 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: make install
    - name: Build the docs site.
      shell: bash    
      run: |
        make docs-validate